# -*- coding: utf-8 -*-
"""CS_4342_Final_Project_Softmax_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mi8boJ2RZrN8NUm_4cYinVbV6VDOJX7E

# Pytorch with the MNIST Dataset - MINST
"""

## import libraries
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision

import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

import numpy as np
import pandas as pd
from sklearn import set_config
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder, label_binarize
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report, roc_auc_score,
    roc_curve, auc, precision_recall_curve, average_precision_score,
    brier_score_loss, f1_score
)
from sklearn.calibration import calibration_curve
from sklearn.base import clone
import matplotlib.pyplot as plt
import seaborn as sns

from flask import Flask, request, jsonify, render_template
from flask_cors import CORS

print(torch.__version__)

# downloading dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction")

print("Path to dataset files:", path)

# Load the data
data = pd.read_csv(path + '/heart.csv')

# Pick target column and feature columns
target = "HeartDisease"
y = data[target]

# numeric and categorical input columns
num_cols = ["Age", "RestingBP", "Cholesterol", "FastingBS", "MaxHR", "Oldpeak"]
cat_cols = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]
X = data.drop(target, axis=1)

# Preprocess + Model Pipeline

# filling in any null values in numerical columns
X[num_cols] = X[num_cols].fillna(X[num_cols].mean())

# filling in any null values in categorical columns
for col in cat_cols:
    X[col] = X[col].fillna(X[col].mode()[0])


# Need to standardize numeric features
# One hot encode categorical features
# Linear regression outputs a continuous score, so we will use a threshold
pre = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ]
)

# Train/test split (stratified using target column)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=27
)

# Full pipeline: preprocessing + logistic regression
logRegSM = Pipeline(steps=[
    ('preprocessor', pre),
    ('classifier', LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200))
])

# train model
logRegSM.fit(X_train, y_train)

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

param_grid = [
    {
        "classifier__solver": ["lbfgs", "newton-cg"],
        "classifier__penalty": ["l2"],
        "classifier__C": [0.01, 0.1, 1, 10, 100],
    },
    {
        "classifier__solver": ["saga"],
        "classifier__penalty": ["l1", "l2"],
        "classifier__C": [0.01, 0.1, 1, 10, 100],
    }
]

grid = GridSearchCV(logRegSM, param_grid, cv=5, scoring="accuracy")
grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best CV Accuracy:", grid.best_score_)

best_model = grid.best_estimator_

# Evaluate on the test set with the tuned threshold
#y_pred_test = logRegSM.predict(X_test)
y_pred_test = best_model.predict(X_test)
y_prob_test = np.clip(y_pred_test, 0, 1)

print("Accuracy:", accuracy_score(y_test, y_pred_test))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_test))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_test))
print("\nClassification Report:\n", classification_report(y_test, y_pred_test))

# Create ROC Curve
y_score = best_model.predict_proba(X_test)[:, 1]

#fpr, tpr, thresholds = roc_curve(y_test, y_score)
fpr, tpr, thresholds = roc_curve(y_test, y_pred_test)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color="blue", label=f"ROC curve (AUC = {roc_auc:.2f})")
plt.plot([0,1], [0,1], color="gray", linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Softmax ROC Curve")
plt.legend(loc="lower right")
plt.show()

app = Flask(__name__)

CORS(app)

@app.route("/")
def home():
    return render_template("website.html")

@app.route("/parse", methods = ['POST'])
def flask_perdict():
    if request.is_json:
        data = request.json
        print(data)
        print(type(data))
        test_set = pd.DataFrame(data,index=[0])
        print(test_set)
        user_input_test = best_model.predict(test_set)
        print(user_input_test)
        if (user_input_test[0]):
            return jsonify({"message": "We are 88% sure that you do have heart disease","recieved data": "We are 88% sure that you do have heart disease" })
        else: 
            return jsonify({
                "message": "We are 88% sure that you do not have heart disease",
                "recieved data": "We are 88% sure that you do not have heart disease"
            })
    else: 
        return jsonify({
            "messge": "error"
        })
    
